apiVersion: v1
kind: Secret
metadata:
  name: app
stringData:
  SA_PASSWORD: db_pass # replace
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
    - port: 1433
      name: database
  selector:
    app: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Express
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app
                  key: SA_PASSWORD
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: data
              mountPath: /var/opt/mssql/data
            - name: log
              mountPath: /var/opt/mssql/log
            - name: secrets
              mountPath: /var/opt/mssql/secrets
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: azurefile # replace
        volumeMode: Block # replace
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi # replace
    - metadata:
        name: log
      spec:
        storageClassName: azurefile # replace
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: secrets
      spec:
        storageClassName: azurefile # replace
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
